name: Update GitHub stats on the website every 3 days

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Execute node script
        run: |
          npm i
          node git_data_fetcher.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name "karthikmurali60"
          git config --global user.email "karthik.murali60@gmail.com"
          git add .
          git commit -m "Update git stats"
          git push
