name: Update GitHub stats on the website every 7 days

on:
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Execute node script
        run: node git_data_fetcher.mjs
